# Site settings
title: Your Screen Is Not Dead
email: yourscreenisnotdead@gmail.com
description: "Three passionate Uptown, NYC friends who love and enjoy movies break down their favorite films from current releases to older classics. No film is off-limits, no matter how obscure. Every week we announce a new film and give you a week to watch it...then we talk about it. This is our contribution to film appreciation."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourscreenisnotdead.com" # the base hostname & protocol for your site
permalink: none
gems:
  - jekyll-redirect-from
  - jekyll-paginate


# Build settings
markdown: kramdown
paginate: 10

# Next Episode Settings
# ------------------------------------------------------------------------
nextMovie: Running Scared
nextMovieLink: http://www.imdb.com/title/tt0404390/?ref_=fn_al_tt_1
